// <auto-generated />
using System;
using AgriMarket.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgriMarket.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520162736_UnifyUserRoles")]
    partial class UnifyUserRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgriMarket.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("boolean");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("ServiceListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsBooked");

                    b.HasIndex("ServiceListingId");

                    b.ToTable("Availabilities");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AreaInHectares")
                        .HasColumnType("numeric");

                    b.Property<Guid>("AvailabilityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceListingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("ServiceListingId");

                    b.HasIndex("Status");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.ConversationParticipant", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConversationId", "UserProfileId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.County", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EhakCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EhakCode")
                        .IsUnique();

                    b.ToTable("Counties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0037",
                            Name = "Harju maakond"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            EhakCode = "0039",
                            Name = "Hiiu maakond"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            EhakCode = "0044",
                            Name = "Ida-Viru maakond"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            EhakCode = "0049",
                            Name = "Jõgeva maakond"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            EhakCode = "0051",
                            Name = "Järva maakond"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            EhakCode = "0056",
                            Name = "Lääne maakond"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            EhakCode = "0059",
                            Name = "Lääne-Viru maakond"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            EhakCode = "0063",
                            Name = "Põlva maakond"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            EhakCode = "0067",
                            Name = "Pärnu maakond"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000a"),
                            EhakCode = "0070",
                            Name = "Rapla maakond"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000b"),
                            EhakCode = "0074",
                            Name = "Saare maakond"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000c"),
                            EhakCode = "0078",
                            Name = "Tartu maakond"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000d"),
                            EhakCode = "0082",
                            Name = "Valga maakond"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000e"),
                            EhakCode = "0084",
                            Name = "Viljandi maakond"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000f"),
                            EhakCode = "0086",
                            Name = "Võru maakond"
                        });
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("HorsePower")
                        .HasColumnType("integer");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ManufactureYear")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("MunicipalityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MunicipalityId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderProfileId");

                    b.HasIndex("SentAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.MessageRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("MessageId", "UserProfileId")
                        .IsUnique();

                    b.ToTable("MessageReads");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Municipality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountyId")
                        .HasColumnType("uuid");

                    b.Property<string>("EhakCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountyId");

                    b.HasIndex("EhakCode")
                        .IsUnique();

                    b.ToTable("Municipalities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0784",
                            Name = "Tallinn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0141",
                            Name = "Anija vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0198",
                            Name = "Harku vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0245",
                            Name = "Jõelähtme vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0296",
                            Name = "Keila linn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0303",
                            Name = "Kiili vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000007"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0338",
                            Name = "Kose vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000008"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0353",
                            Name = "Kuusalu vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000009"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0424",
                            Name = "Loksa linn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000a"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0431",
                            Name = "Lääne-Harju vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000b"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0446",
                            Name = "Maardu linn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000c"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0651",
                            Name = "Raasiku vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000d"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0653",
                            Name = "Rae vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000e"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0718",
                            Name = "Saku vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000000f"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0726",
                            Name = "Saue vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000010"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            EhakCode = "0890",
                            Name = "Viimsi vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000011"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            EhakCode = "0205",
                            Name = "Hiiumaa vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000012"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            EhakCode = "0130",
                            Name = "Alutaguse vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000013"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            EhakCode = "0251",
                            Name = "Jõhvi vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000014"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            EhakCode = "0321",
                            Name = "Kohtla-Järve linn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000015"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            EhakCode = "0442",
                            Name = "Lüganuse vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000016"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            EhakCode = "0511",
                            Name = "Narva linn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000017"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            EhakCode = "0514",
                            Name = "Narva-Jõesuu linn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000018"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            EhakCode = "0735",
                            Name = "Sillamäe linn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000019"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            EhakCode = "0803",
                            Name = "Toila vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000001a"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            EhakCode = "0247",
                            Name = "Jõgeva vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000001b"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            EhakCode = "0486",
                            Name = "Mustvee vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000001c"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            EhakCode = "0618",
                            Name = "Põltsamaa vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000001d"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000005"),
                            EhakCode = "0255",
                            Name = "Järva vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000001e"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000005"),
                            EhakCode = "0567",
                            Name = "Paide linn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000001f"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000005"),
                            EhakCode = "0834",
                            Name = "Türi vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000020"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000006"),
                            EhakCode = "0184",
                            Name = "Haapsalu linn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000021"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000006"),
                            EhakCode = "0441",
                            Name = "Lääne-Nigula vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000022"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000007"),
                            EhakCode = "0191",
                            Name = "Haljala vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000023"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000007"),
                            EhakCode = "0272",
                            Name = "Kadrina vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000024"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000007"),
                            EhakCode = "0663",
                            Name = "Rakvere linn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000025"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000007"),
                            EhakCode = "0661",
                            Name = "Rakvere vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000026"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000007"),
                            EhakCode = "0792",
                            Name = "Tapa vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000027"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000007"),
                            EhakCode = "0897",
                            Name = "Vinni vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000028"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000007"),
                            EhakCode = "0903",
                            Name = "Viru-Nigula vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000029"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000007"),
                            EhakCode = "0928",
                            Name = "Väike-Maarja vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000002a"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000008"),
                            EhakCode = "0284",
                            Name = "Kanepi vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000002b"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000008"),
                            EhakCode = "0622",
                            Name = "Põlva vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000002c"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000008"),
                            EhakCode = "0708",
                            Name = "Räpina vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000002d"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000009"),
                            EhakCode = "0214",
                            Name = "Häädemeeste vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000002e"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000009"),
                            EhakCode = "0305",
                            Name = "Kihnu vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000002f"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000009"),
                            EhakCode = "0430",
                            Name = "Lääneranna vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000030"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000009"),
                            EhakCode = "0638",
                            Name = "Põhja-Pärnumaa vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000031"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000009"),
                            EhakCode = "0624",
                            Name = "Pärnu linn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000032"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000009"),
                            EhakCode = "0712",
                            Name = "Saarde vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000033"),
                            CountyId = new Guid("a0000000-0000-0000-0000-000000000009"),
                            EhakCode = "0809",
                            Name = "Tori vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000034"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000a"),
                            EhakCode = "0293",
                            Name = "Kehtna vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000035"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000a"),
                            EhakCode = "0317",
                            Name = "Kohila vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000036"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000a"),
                            EhakCode = "0503",
                            Name = "Märjamaa vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000037"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000a"),
                            EhakCode = "0669",
                            Name = "Rapla vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000038"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000b"),
                            EhakCode = "0478",
                            Name = "Muhu vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000039"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000b"),
                            EhakCode = "0714",
                            Name = "Saaremaa vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000003a"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000c"),
                            EhakCode = "0171",
                            Name = "Elva vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000003b"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000c"),
                            EhakCode = "0283",
                            Name = "Kambja vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000003c"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000c"),
                            EhakCode = "0291",
                            Name = "Kastre vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000003d"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000c"),
                            EhakCode = "0432",
                            Name = "Luunja vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000003e"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000c"),
                            EhakCode = "0528",
                            Name = "Nõo vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000003f"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000c"),
                            EhakCode = "0586",
                            Name = "Peipsiääre vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000040"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000c"),
                            EhakCode = "0793",
                            Name = "Tartu linn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000041"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000c"),
                            EhakCode = "0796",
                            Name = "Tartu vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000042"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000d"),
                            EhakCode = "0557",
                            Name = "Otepää vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000043"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000d"),
                            EhakCode = "0824",
                            Name = "Tõrva vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000044"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000d"),
                            EhakCode = "0855",
                            Name = "Valga vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000045"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000e"),
                            EhakCode = "0480",
                            Name = "Mulgi vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000046"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000e"),
                            EhakCode = "0615",
                            Name = "Põhja-Sakala vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000047"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000e"),
                            EhakCode = "0899",
                            Name = "Viljandi linn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000048"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000e"),
                            EhakCode = "0901",
                            Name = "Viljandi vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000049"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000f"),
                            EhakCode = "0142",
                            Name = "Antsla vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000004a"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000f"),
                            EhakCode = "0698",
                            Name = "Rõuge vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000004b"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000f"),
                            EhakCode = "0732",
                            Name = "Setomaa vald"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000004c"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000f"),
                            EhakCode = "0919",
                            Name = "Võru linn"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-00000000004d"),
                            CountyId = new Guid("a0000000-0000-0000-0000-00000000000f"),
                            EhakCode = "0917",
                            Name = "Võru vald"
                        });
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReviewedProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("ReviewedProfileId");

                    b.HasIndex("ReviewerProfileId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.ServiceListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PricePerHectare")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ServiceCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("LocationId");

                    b.HasIndex("ServiceCategoryId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ServiceListings");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.ServiceListingEquipment", b =>
                {
                    b.Property<Guid>("ServiceListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.HasKey("ServiceListingId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ServiceListingEquipments");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId", "Role")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Availability", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.ServiceListing", "ServiceListing")
                        .WithMany("Availabilities")
                        .HasForeignKey("ServiceListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceListing");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Booking", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.Availability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriMarket.Domain.Entities.UserProfile", "ClientProfile")
                        .WithMany("ClientBookings")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriMarket.Domain.Entities.ServiceListing", "ServiceListing")
                        .WithMany()
                        .HasForeignKey("ServiceListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Availability");

                    b.Navigation("ClientProfile");

                    b.Navigation("ServiceListing");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriMarket.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Equipments")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Location", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.Municipality", "Municipality")
                        .WithMany("Locations")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Message", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriMarket.Domain.Entities.UserProfile", "SenderProfile")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("SenderProfile");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.MessageRead", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.Message", "Message")
                        .WithMany("MessageReads")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriMarket.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("MessageReads")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Municipality", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.County", "County")
                        .WithMany("Municipalities")
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("County");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Payment", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("AgriMarket.Domain.Entities.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.AppUser", "AppUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Review", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("AgriMarket.Domain.Entities.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriMarket.Domain.Entities.UserProfile", "ReviewedProfile")
                        .WithMany()
                        .HasForeignKey("ReviewedProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriMarket.Domain.Entities.UserProfile", "ReviewerProfile")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ReviewedProfile");

                    b.Navigation("ReviewerProfile");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.ServiceListing", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgriMarket.Domain.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany()
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriMarket.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("ServiceListings")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("ServiceCategory");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.ServiceListingEquipment", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.Equipment", "Equipment")
                        .WithMany("ServiceListingEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriMarket.Domain.Entities.ServiceListing", "ServiceListing")
                        .WithMany("ServiceListingEquipments")
                        .HasForeignKey("ServiceListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("ServiceListing");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.AppUser", "AppUser")
                        .WithOne("Profile")
                        .HasForeignKey("AgriMarket.Domain.Entities.UserProfile", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("AgriMarket.Domain.Entities.AppUser", "AppUser")
                        .WithMany("Roles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.County", b =>
                {
                    b.Navigation("Municipalities");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("ServiceListingEquipments");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Message", b =>
                {
                    b.Navigation("MessageReads");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.Municipality", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.ServiceListing", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("ServiceListingEquipments");
                });

            modelBuilder.Entity("AgriMarket.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("ClientBookings");

                    b.Navigation("ConversationParticipants");

                    b.Navigation("Equipments");

                    b.Navigation("MessageReads");

                    b.Navigation("Reviews");

                    b.Navigation("SentMessages");

                    b.Navigation("ServiceListings");
                });
#pragma warning restore 612, 618
        }
    }
}
